### ISSUE TITLE
Unable to turn off a given type of notification 

### ISSUE THREAD

**Issue by erikdoe** [erikdoe/ccmenu#1]
Currently it's not possible to turn off some kind of event notifications, f.e. one do not interested in successful builds. Earlier version had this option, now only the sound alert can be customized or turned off not the hole notification of a given state.

[copied from: https://sourceforge.net/p/ccmenu/bugs/18/]

**Comment by Lukx** [comment]
+1 This would be brilliantly useful

**Comment by fuzzyducky** [comment]
+1

**Comment by erikdoe** [comment]
I have implemented this now. A pre-release is available here: https://github.com/erikdoe/ccmenu/releases/tag/v1.10d1

Any feedback welcome.

**Comment by Lukx** [comment]
thank you! I have installed it and love the way you implemented the settings menu. It seems to work as expected right now, I'll closely monitor it through the day though. If you don't hear from me, I have not found any issues :+1:
