### ISSUE TITLE
incompatibilities with dark interface on MacOS Mojave

### ISSUE THREAD

**Issue by ssbarnea** [erikdoe/ccmenu#101]
Apparently there are few problems using CCMenu on MacOS Mojave which is close to being released.
<img width="597" alt="ccmenu-dark" src="https://user-images.githubusercontent.com/102495/44579977-24d70280-a790-11e8-8bab-5743abf8a33d.png">

**Comment by TheKevJames** [comment]
For what its worth -- I'm currently on Mojave in dark mode and I can't replicate this issue. Perhaps it was a bug in a pre-release Mojave version?

**Comment by ssbarnea** [comment]
That bugs is too old to matter, I am on Catalina and it works fine, closing.
