### ISSUE TITLE
Support redirects for Jenkins `/cc.xml` to `/cc.xml/`

### ISSUE THREAD

**Issue by richellis** [erikdoe/ccmenu#108]
Jenkins changed their CCmenu support by moving it to a plugin (https://github.com/jenkinsci/cctray-xml-plugin) in Jenkins 2.173. 

When my Jenkins instance was updated to 2.173 and the new plugin was installed, all of the jobs I was monitoring in CCmenu stopped working, I would get a "forbidden" error. I finally found this statement in the plugin readme (emphasis added):
>The links point to the URLs `/cc.xml/` and `/cc.xml/?recursive` which are similar to those previously in core. **`/cc.xml` now redirects to `/cc.xml/`**, so any client that supports HTTP redirects will be able to continue to use old URLs.

I was able to restore functionality by editing each job and adding a trailing `/`. Does CCmenu  support redirects? If not, it would be great if it did.

If it does, then this issue can be closed and I'll just assume it was a different configuration issue with my Jenkins server (I don't run the server so I have no real way to debug further). Just wanted to report it here in case it helps others.

**Comment by erikdoe** [comment]
Apologies for the late reply. CCMenu uses the standard Apple-provided classes and those follow redirects. So, it really sounds like an issue with your setup.
