### ISSUE TITLE
Add option to only use color in menu bar icons for unsuccessful builds

### ISSUE THREAD

**Issue by TravisCarden** [erikdoe/ccmenu#110]
I would like to see the ability to get colored icons for build failures so they draw my attention but _not_ for successful builds so they don't stand out from my other monochrome menu bar icons and thus draw regularly my attention when there's nothing that requires it. (p.s. - First time in this issue queue. Thanks for the awesome app! 😃)

**Comment by donatj** [comment]
I would love this as well.

**Comment by erikdoe** [comment]
I've added this feature. Can you let me know whether it works for you?

**Comment by TravisCarden** [comment]
I'd love to, @erikdoe. How would I go about getting the test version? (I'm not a Mac developer such that I could build a binary myself.)

**Comment by erikdoe** [comment]
Okay, I'll try to get a preview version up on the Github releases page. This might take a few days because I need to get updated signing keys.

**Comment by TravisCarden** [comment]
Thank, @erikdoe. Take your time. I'm patient. 😃

**Comment by erikdoe** [comment]
I've now created a pre-release here on Github. https://github.com/erikdoe/ccmenu/releases

**Comment by TravisCarden** [comment]
Thanks, @erikdoe. It works beautifully!

**Comment by erikdoe** [comment]
Released. Finally!
