### ISSUE TITLE
Per-connection Proxy Setting

### ISSUE THREAD

**Issue by jberger** [erikdoe/ccmenu#111]
For some work ci systems, I need to use a proxy specific to that connection. In the browser I use FoxyProxy. It would be lovely to have a similar setting in CCMenu so that I can use that proxy in CCMenu as well.

**Comment by erikdoe** [comment]
I understand the request, but I will say that it's not super likely I'll implement it. The use case seems very niche, but it would add to the complexity of the UI.

**Comment by jberger** [comment]
Thanks for looking at this ticket. I can understand that response. I wish I could get the OS to handle per-host proxying for me.

If the only concern is UI complexity (which is a real concern) you could maybe put it behind an "advanced" collapser? Maybe the username/password could go there too and actually simplify the standard case?

**Comment by erikdoe** [comment]
That is a possibility, but someone has to program all this. ;-)

Given that you also need an add-on in the browser, could you not just run nginx or similar on your computer as a local proxy that knows what proxy to use? That would solve your problem for Firefox and CCMenu.

**Comment by jberger** [comment]
> That is a possibility, but someone has to program all this. ;-)
> 

I always hate putting in feature requests for software in a language I don't know, because I know the feeling :/

> Given that you also need an add-on in the browser, could you not just run nginx or similar on your computer as a local proxy that knows what proxy to use? That would solve your problem for Firefox and CCMenu.

That is a very interesting idea, I hadn't thought of that!
