### ISSUE TITLE
Green icons too light on Big Sur

### ISSUE THREAD

**Issue by ktwbc** [erikdoe/ccmenu#113]
Due to color changes in the Big Sur update of MacOS, the green success icon is now too light and is blending into the background. It would be nice to simply have a setup option for an RGB value to make dot colors adjustable.

<img width="158" alt="Screen Shot 2020-11-16 at 6 52 45 PM" src="https://user-images.githubusercontent.com/624611/99326041-1e377880-283d-11eb-812e-ec483bd65e74.png">

**Comment by erikdoe** [comment]
Thanks. Haven't upgraded to Big Sur myself but will look into this in the coming weeks. In the meantime you could use the black and white option. (It's not the same, I know.)

**Comment by erikdoe** [comment]
I've changed the green a little bit. If you known how to build CCMenu, could you try and see if it works for you?

Ultimately, it seems that with Big Sur the icons need to work with a larger range of background colours. Not entirely sure what to do about it, to be honest.

**Comment by erikdoe** [comment]
Released now.

**Comment by ktwbc** [comment]
I was going to reply earlier, that long term maybe just having a way to put in your own RGB values that way they could be customized per display. Because it’s semi-transparent and depends on the desktop picture the person has, it will be hard to get something perfect for everyone.
