### ISSUE TITLE
Failure to parse xml file from BuildKite

### ISSUE THREAD

**Issue by Alex-EEE** [erikdoe/ccmenu#114]
Hi,

BuildKite works with the basic URL, but you can append a branch name to the URL and just get status for that branch.  I tested this in a browser and it worked, therefore, ccmenu was unable to parse the following XML file:
```
<Projects>
<Project name="studio (accelerometer-quantized)" activity="Building" lastBuildStatus="Unknown" lastBuildLabel="7316" lastBuildTime="2021-02-05T17:47:07+00:00" webUrl="https://buildkite.com/edgeimpulse/studio/builds?branch=accelerometer-quantized"/>
</Projects>
```

**Comment by erikdoe** [comment]
Can you share the error message? I tried this and fed the exact XML you provided to CCMenu and it worked.

**Comment by Alex-EEE** [comment]
"An error occurred when retrieving the project status". "No project information provided by server"

That's a window that popped up.  Is there an error or debug log I can view while CCMenu is running?

**Comment by erikdoe** [comment]
Is it possible that the server has changed the name for the project? A feed can contain the status of multiple projects, and it looks like CCMenu doesn't find the project in the feed anymore. The feed contains info for a project named `studio (accelerometer-quantized)`. Is this the name of the project you want to monitor?

**Comment by Alex-EEE** [comment]
aaah yes, that's what's happening.  We're using BuildKite, and you can get an XML feed per branch...but that also changes the project name, unfortunately.  

What I was doing was just replacing the URL on the existing project.  But that's what caused the problem.  I'll just have to add a new project for each new branch I want to monitor.

Thanks for the help!

**Comment by erikdoe** [comment]
I've changed the error message a bit. Hopefully that will help in cases like this.
