### ISSUE TITLE
background alerts are blocking

### ISSUE THREAD

**Issue by sodul** [erikdoe/ccmenu#115]
Once in a while we get an alert from CCMenu. Until OK is clicked on the alert the statuses are no longer being refreshed and other than that there is no visual clue that an alert popped up.

Since CCMenu is an app listed under cmd+Tab, the workaround it to type `CCMenu` in Spotlight to show the alert so we can click it.

We think that such popups should not be preventing the statuses to be refreshed, at least not all of them, and that the menu should reflect that a popup is present and requires user attention.

**Comment by erikdoe** [comment]
Yes, that sounds like a problem, and there should probably be a different solution for alerting the user. Just out of curiosity, what kind of alerts are you seeing?

**Comment by sodul** [comment]
![image](https://user-images.githubusercontent.com/1504511/108279860-22bc4780-7132-11eb-9c68-a1b88e183f76.png)
We have a jenkins instance behind VPN so if I click on on the status entry of one of the pipelines while off VPN, this pops up in the background and CCMenu is no longer functional until I 'open' CCMenu through Spotlight to click OK.

**Comment by erikdoe** [comment]
A solution could be to change alerts to system notifications when CCMenu is in the background, right?

**Comment by sodul** [comment]
That seems very appropriate, especially considering CCMenu already alerts through the system notifications for the state of the builds.

**Comment by erikdoe** [comment]
Looking at this in more detail I realised that this class of errors is only shown when the user clicks on a menu item. I think it is appropriate for CCMenu to bring itself to the front, which is the change I made now. This should make the alert visible.
