### ISSUE TITLE
Jenkins authentication not working

### ISSUE THREAD

**Issue by cmivxx** [erikdoe/ccmenu#12]
I have Jenkins running on a local box using built-in matrix security and the main user has full permissions.  I cannot get your app to auth with either the username/password conbo in the auth box or the user/api key in the url box.  Alternatively, I cannot access cc.xml using the api-key/url method you guys described.  I can only imagine that your auth methods are broken for the app.

Jenkins: 1.597
CCMenu: 1.8 (266a)
OSX: 10.10.1

Love the tool and would love to make it work without exposing job details to the world.

Thanks!

**Comment by erikdoe** [comment]
CCMenu uses the Apple libraries for authentication, which I believe implement the HTTP standards pretty well. Jenkins is known to be somewhat special (see #9). If this is the same issue you are seeing it might be good to provide feedback to the Jenkins team. In either case, I am willing to put some code into CCMenu to work around the Jenkin's flaws, but this may take a bit of time. Any help would be appreciated.

**Comment by cmivxx** [comment]
Well, I'm not a OSX Dev, so I'm not sure how much I can actually help code-wise, however this auth bug is present on most of the other little widgets that are available on the app-store, etc.  So I found this:  The 403 error that comes back has some more information that I haven't seen mentioned here before:  Maybe this will lead you in the right direction.

```html
<html><head><meta http-equiv='refresh' content='1;url=/loginEntry?from=%2Fcc.xml%2Fapi%2Fjson%3Ftree%3DdisplayName%2Cname%2Cbuilds%255Bresult%2Cnumber%255D'/><script>window.location.replace('/loginEntry?from=%2Fcc.xml%2Fapi%2Fjson%3Ftree%3DdisplayName%2Cname%2Cbuilds%255Bresult%2Cnumber%255D');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:
  
Permission you need to have (but didn't): hudson.model.Hudson.Read
 ... which is implied by: hudson.security.Permission.GenericRead
 ... which is implied by: hudson.model.Hudson.Administer
-->

</body></html>
```

**Comment by samdeane** [comment]
I have a similar problem. Versions prior to 1.8 seemed to work fine for me, but 1.8 is broken and just gives me back 403 when I try to talk to our Jenkins server :(

**Comment by erikdoe** [comment]
I still don't understand why the changes in CCMenu 1.8 have this effect. However, in the discussion of #11 we found a workaround and this workaround is in the latest source code. Once I find a bit of time to clean this up, I'll submit a new version to the app store.

**Comment by erikdoe** [comment]
So, finally found the time to do this. And I found out that the implementation I did a couple of weeks ago only worked due to a lucky coincidence. If anyone can try the current version and confirm it works, please let me know. I will then submit it to the App Store right away.

**Comment by erikdoe** [comment]
Fixed in CCMenu 1.9.

**Comment by patroqueeet** [comment]
hey, at least not working for me.

I'm on:
![screen shot 2015-03-18 at 10 26 13](https://cloud.githubusercontent.com/assets/2073086/6706848/36139ac8-cd59-11e4-81f0-f06189532f85.png)

and get:

![screen shot 2015-03-18 at 10 26 39](https://cloud.githubusercontent.com/assets/2073086/6706862/6717fd30-cd59-11e4-86b6-764f0e11d0b9.png)

**Comment by erikdoe** [comment]
@patroqueeet Could you send me the output from the following command:

    curl -i <url goes here>

The output should look somehow like this:

	HTTP/1.1 403 Forbidden
	Set-Cookie: JSESSIONID.3c92b5df=1kbd0izsqblyx1uyct4cn0fzsr;Path=/;HttpOnly
	Expires: Thu, 01 Jan 1970 00:00:00 GMT
	Content-Type: text/html;charset=UTF-8
	X-Hudson: 1.395
	X-Jenkins: 1.597
	X-Jenkins-Session: 43697f59
	X-Hudson-CLI-Port: 51024
	X-Jenkins-CLI-Port: 51024
	X-Jenkins-CLI2-Port: 51024
	X-You-Are-Authenticated-As: anonymous
	X-You-Are-In-Group: 
	X-Required-Permission: hudson.model.Hudson.Read
	X-Permission-Implied-By: hudson.security.Permission.GenericRead
	X-Permission-Implied-By: hudson.model.Hudson.Administer
	Content-Length: 805
	Server: Jetty(winstone-2.8)
	
	<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fcc.xml'/><script>window.location.replace('/login?from=%2Fcc.xml');</script></head><body style='background-color:white; color:white;'>


	Authentication required
	

	</body></html>

**Comment by patroqueeet** [comment]
Dear,

here we go:

```
HTTP/1.1 403 Forbidden
Set-Cookie: JSESSIONID.a08c94c3=167t5qfy5ezo7fobunzpinorv;Path=/;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: text/html;charset=UTF-8
X-Hudson: 1.395
X-Jenkins: 1.593
X-Jenkins-Session: 97cf6d8d
X-Hudson-CLI-Port: 35521
X-Jenkins-CLI-Port: 35521
X-Jenkins-CLI2-Port: 35521
X-You-Are-Authenticated-As: anonymous
X-You-Are-In-Group:
X-Required-Permission: hudson.model.Hudson.Read
X-Permission-Implied-By: hudson.security.Permission.GenericRead
X-Permission-Implied-By: hudson.model.Hudson.Administer
Content-Length: 793
Server: Jetty(winstone-2.8)

<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2F'/><script>window.location.replace('/login?from=%2F');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:

Permission you need to have (but didn't): hudson.model.Hudson.Read
 ... which is implied by: hudson.security.Permission.GenericRead
 ... which is implied by: hudson.model.Hudson.Administer
-->

```

**Comment by erikdoe** [comment]
Okay, can you now try

    curl -i -H "Authorization: Basic Zm9vOnBhc3N3MHJkCg==" <url goes here>

This is trying to authenticate with user *foo* and the password *passw0rd*. I'm interested to see the response to understand whether the credentials aren't accepted or whether your installation somehow doesn't do basic auth.

For even more info you could use the correct header for your username and password. Build a string like this "username:password" and then base64 encode that string. Replace the last bit in the header in the command above, ie. `Zm9vOnBhc3N3MHJkCg==`, with your credentials in that base64 encoded form.

**Comment by patroqueeet** [comment]
```
curl -i -H "Authorization: Basic Zm9vOnBhc3N3MHJkCg==" myurl.com:8080
HTTP/1.1 401 Invalid password/token for user: foo
WWW-Authenticate: Basic realm="Jenkins"
Content-Type: text/html;charset=ISO-8859-1
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 1419
Server: Jetty(winstone-2.8)

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 401 Invalid password/token for user: foo</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /. Reason:
<pre>    Invalid password/token for user: foo</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

</body>
</html>
```

and with my credentials:

```
...
```

damn. got another 401 with my credentials, played around with the base64 encoding. found the `curl` working after 7 attempts and thought let's try with ccMenu again. Worked. Damn. thanks for the help! excellent maintained package!
