### ISSUE TITLE
invalid SSL certificate promps should now be ever showed

### ISSUE THREAD

**Issue by ssbarnea** [erikdoe/ccmenu#14]
Almost every time I connect to a WiFi with a captive portal I get a popup from CCMenu that complains about invalid certificates.

This should never happen. If CCMenu would encounter this it should only assume that the network connection is down, nothing more prompts for SSL certificates are only a bad user experience and a high security risks. Any invalid SSL certificate should be considered a failure, no prompts at all. Less Is More ;)

![screenshot 2015-01-26 09 24 19](https://cloud.githubusercontent.com/assets/102495/5897572/2dcaf0ee-a53d-11e4-9f9f-8fabdc82ab5e.png)

**Comment by erikdoe** [comment]
Interesting. What you want is the default behaviour of Apple's networking libraries and it is what CCMenu did in the past. CCMenu 1.8 is the first version that gives users the option to accept "invalid" certificates.

The reason why this option was added is that users requested it; and it has been requested for a long time, see https://sourceforge.net/p/ccmenu/feature-requests/2/ for example. (The ensuing discussion is somewhat interesting, too.) Why would people want this feature? Well, it seems that a lot of people use self-signed certs on their CI servers, and they don't sign these with their own root cert or they don't distribute the root cert to their machines. In either case, CCMenu ends up being configured to make HTTPS requests without being able to verify the cert.

Now, I understand that captive portals cause the dialog to appear. (I get similar panels from Apple's calendar app, too.) However, captive portals are an ever bigger scourge than people who don't manage their own certs well. So, given that you basically have to make a choice between doing the right thing for captive portals and doing the right thing for unverifiable certs, I think supporting the latter is more helpful for the user base of CCMenu. YMMV.

I should add that I understand that popping up dialogues allowing users to add security exceptions is bad. You could say that this is training people to accept broken security. Again, this is a trade off. The users for CCMenu are developers, they are more likely to be aware of what they are doing. And they are either the ones who set up the self-signed certs in the first place, or they are in no position to get the cert policy in the organisation changed. So, failing on an unverifiable cert makes CCMenu unusable for them.

**Comment by ssbarnea** [comment]
I am glad that we are on the same page hear.

I know, in the past I did the same regarding certificates, but was years ago.

As of 2015, I do think that putting a self-signed certificate is something wrong. People could even get free or test valid certificates. A self signed one is a recipe for insecurity.

Yes, pop-ups must die! ;)

**Comment by erikdoe** [comment]
In a future version I'll add an advanced preference that says something along the lines of "never ask me when a cert is not verifiable, just reject it". Keeping this issue open as an enhancement request.

**Comment by mahemoff** [comment]
+1 - thanks for adding it as an enhancement as I've been getting these popups while relying on hotel wifi. It's more common for background apps to change the display under such circumstances, e.g. show a broken padlock or disconnected icon as the situation warrants. The current gray indicator is fine enough for me anyway.

**Comment by erikdoe** [comment]
I've done this now. Please check out the pre-release at https://github.com/erikdoe/ccmenu/releases

**Comment by erikdoe** [comment]
Closing. Presumed fixed.

**Comment by mahemoff** [comment]
Thanks for the fix @erikdoe. I didn't have the conditions to check it but will let you know if any issues with it in the future.

**Comment by ssbarnea** [comment]
I can confirm that the bug is still present in version 10.11.3! Can we get a fix please?

**Comment by erikdoe** [comment]
@ssbarnea Which bug do you refer to? This issue was about CCMenu asking you to accept or reject unverifiable certs. The fix implemented is an advanced preference named "Ask when certificate is unverifiable". It's on by default but when you turn it off CCMenu should never bother you with certificate alerts. Are you maybe talking about a different bug?
