### ISSUE TITLE
Tagging releases?

### ISSUE THREAD

**Issue by miketheman** [erikdoe/ccmenu#15]
Hi there!

I'm trying to tackle the ccmenu-jenkins-authentication-via-github hurdle, and from the CHANGES.txt is appears that some work was done in 1.9 to make things better, as well as some closed issues.

It's not clear when a changeset was released - if at all - any chance you might consider adding release tags when cutting a release for the App Store?

(Also, is there some way I can grab the code, compile/install it myself to test the behavior?

**Comment by erikdoe** [comment]
Yes, I will do that going forward. CCMenu has not seen a release since I moved it from SourceForge/Subversion over to Github. You can see the App Store releases, though, because there is a branch for each of the App Store releases.

I should clarify in CHANGES that 1.9 is unreleased as of now.

**Comment by erikdoe** [comment]
Release 1.9 is out and has been tagged.
