### ISSUE TITLE
Semaphore Integration

### ISSUE THREAD

**Issue by domness** [erikdoe/ccmenu#17]
Unfortunately we have most of our projects on [Semaphore](https://semaphoreapp.com/), any chance of getting integration with them?

**Comment by erikdoe** [comment]
If Semaphore supports the "cctray" feed format then it will just work. If Semaphore only provides its own proprietary API then CCMenu will not be able to interact with it. In that case, it might make sense to request that Semaphore provides info in the "cctray" format, which is a de-facto standard implemented by most CI servers.

**Comment by domness** [comment]
Got it, had a poke around and it seems it works!

Documentation for Semaphore here: [https://github.com/renderedtext/semaphore-docs-new/blob/master/source/docs/cctry.md](https://github.com/renderedtext/semaphore-docs-new/blob/master/source/docs/cctry.md)

**Comment by erikdoe** [comment]
Thanks! I think I should start a wiki page with info about the various CI servers...

**Comment by domness** [comment]
Sounds a good idea :)
