### ISSUE TITLE
CircleCI project with token does not work with CCMenu

### ISSUE THREAD

**Issue by stanley90** [erikdoe/ccmenu#19]
I added a project to CCMenu using this form of URL:
https://circleci.com/gh/:owner/:repo.cc.xml?circle-token=:circle-token
but CCMenu does not connect to this repo. Also tried different URLs but none worked. Am I doing something wrong?

**Comment by erikdoe** [comment]
A link to set up instructions for CircleCI can be found on the Supported Servers page on the wiki (https://github.com/erikdoe/ccmenu/wiki/Supported-Servers). If the instructions don't work it might make sense to ask the CircleCI team to correct the instructions.

**Comment by stanley90** [comment]
I just found out that the URL doesn't show an expected result in the browser either, so the problem is really not in CCMenu.
