### ISSUE TITLE
Support for easy registration using URL scheme

### ISSUE THREAD

**Issue by ayufan** [erikdoe/ccmenu#22]
It would be nice to have URL scheme registered within CCMenu that would allow to register by clicking link on web: ccmenu://api.travis-...

**Comment by erikdoe** [comment]
I have implemented this now. CCMenu registers two URL schemes, namely `ccmenu+http` and `ccmenu+https`. The rest of the URL should be a cctray formatted feed. For example, if your CI server has a feed for projects at `https://myserver.example.org/cctray.xml` then the URL for CCMenu should be `ccmenu+https://myserver.example.org/cctray.xml`.

When a link with one of those scheme is opened, by clicking in a web browser for example, CCMenu opens the add projects sheet in its preferences, and tries to display the projects contained in the corresponding feed.

**Please note:** If you install a pre-release version of CCMenu that has this feature in addition to an older version that doesn't have this feature, and no version of CCMenu is running, and you try to open such a URL, chances are that Mac OS will launch the wrong version of CCMenu and nothing will happen. Until this is in a released version, it might be necessary to have the right version, and only the right version, of CCMenu running.

**Comment by erikdoe** [comment]
Released in CCMenu 13.0.
