### ISSUE TITLE
Support a happier sounds for options for Alerting when build is Fixed or Green.

### ISSUE THREAD

**Issue by haysclark** [erikdoe/ccmenu#25]
There isn't a good sound file for when the build is green or when someone has fixed the build.  It would be nice if we could pick from a couple happier sounds when you want an Alert that is bringing good news. :gift:

**Comment by erikdoe** [comment]
CCMenu shows the sound files available in the libraries on your system / account. If you put happier sounds into, for example, `~/Library/Sounds` then you can choose them in CCMenu's preferences.
