### ISSUE TITLE
URL concatenation is incorrect with a period in the username

### ISSUE THREAD

**Issue by kennymac** [erikdoe/ccmenu#30]
The behaviour of the auth screen has issues - 

- even with "use URL as entered above" selected, the user @ values are propagated into the Feed URL field
- My user contains a period, user.name, this isn't being parsed correctly
- As the user and password fields are edited, multiple values are embedded into the 
<img width="480" alt="screen shot 2015-07-28 at 4 05 51 pm" src="https://cloud.githubusercontent.com/assets/745019/8924605/a340199a-3542-11e5-8aec-780c82ad6e84.png">

**Comment by erikdoe** [comment]
The way things are currently implemented the user name has to be part of the URL; and this is known to work. What is broken is the handling of certain characters when typed into the user name field. I've just verified that typing the % and \ characters results in some pretty unpredictable URL rewriting. I'll see what I can do to fix this.

Regarding your case, though, why do you have to use the % character? Can you not just type ken.mccormack into the user field? I've tested and using a dot works fine. Side question: why %34? That's just a representation for the character 4, isn't it?

**Comment by erikdoe** [comment]
Fixed in https://github.com/erikdoe/ccmenu/releases/tag/v1.10.1d1
