### ISSUE TITLE
Aborted builds show up as failed in the menubar

### ISSUE THREAD

**Issue by timmfin** [erikdoe/ccmenu#32]
It seems like aborted builds show up as failed in the menu. I think it would make more sense to show a gray icon instead of a red one for aborted builds (aborting isn't necessarily a bad thing).

For example, this is what my menu looks like:

![image](https://cloud.githubusercontent.com/assets/60455/9584014/99eab5bc-4fdc-11e5-8c3e-0cb890a70dc9.png)

... for a job who's last build was merely aborted:

![image](https://cloud.githubusercontent.com/assets/60455/9584035/bd068a94-4fdc-11e5-859b-3060c4751d52.png)

Another view, from the project window where it says that build "failed" despite it only being aborted (note 1:55pm is 5:55pm because my computer is in EST while the build server is in UTC):

![image](https://cloud.githubusercontent.com/assets/60455/9584049/d5316882-4fdc-11e5-8ec1-6dbc0c5d84a8.png)

**Comment by erikdoe** [comment]
CCMenu is tied to the information it gets from the CI server. It doesn't have all the information available to the server internally. Could you include a copy of the XML feed that the server sends on aborted builds? Just take the feed URL and retrieve it using curl or similar, e.g. `curl -i <the_feed_url>`.

**Comment by timmfin** [comment]
Interesting, in the XML feed I see this:

```xml
<Project activity="Sleeping" lastBuildLabel="12" lastBuildStatus="Failure" lastBuildTime="2015-08-26T17:55:03Z" name="EarlyRequesterJS" webUrl="https://<INTERNAL DOMAIN>/jenkins/job/EarlyRequesterJS/"/>
```

Which unfortunately, doesn't tell you anything about it being aborted. But if I hit the Jenkins API directly for that job there is at least some more helpful information:

```xml
  ...
  <color>aborted</color>
  <healthReport>
    <description>Build stability: No recent builds failed.</description>
    <iconClassName>icon-health-80plus</iconClassName>
    <iconUrl>health-80plus.png</iconUrl>
    <score>100</score>
  </healthReport>
  <lastBuild>
    <number>12</number>
    <url>https://<INTERNAL DOMAIN>/jenkins/job/EarlyRequesterJS/12/</url>
  </lastBuild>
  <lastCompletedBuild>
    <number>12</number>
    <url>https://<INTERNAL DOMAIN>/jenkins/job/EarlyRequesterJS/12/</url>
  </lastCompletedBuild>
  <lastStableBuild>
    <number>11</number>
    <url>https://<INTERNAL DOMAIN>/jenkins/job/EarlyRequesterJS/11/</url>
  </lastStableBuild>
  <lastSuccessfulBuild>
    <number>11</number>
    <url>https://<INTERNAL DOMAIN>/jenkins/job/EarlyRequesterJS/11/</url>
  </lastSuccessfulBuild>
  <lastUnsuccessfulBuild>
    <number>12</number>
    <url>https://<INTERNAL DOMAIN>/jenkins/job/EarlyRequesterJS/12/</url>
  </lastUnsuccessfulBuild>
  ...
```

So in that, there is some useful information (the `<color>` and `<healthReport>` elements). But if you are only fetching the feed, well then I don't know if there is anything you can do to fix this.

**Comment by erikdoe** [comment]
And that is the problem. The feed format was created a long time ago (2002) and never had a community that allowed it to evolve. You had _n_ servers and _m_ clients and the only way, without a managing group, to remain compatible was to stand still. 

Now that gocd is open source, I have considered trying to see evolution of the feed format by adding new features to gocd and CCMenu, in the hope others would pick them up. This hasn't really happened yet.
