### ISSUE TITLE
App Transport Security policy problem with CCMenu 1.10.1

### ISSUE THREAD

**Issue by anadin** [erikdoe/ccmenu#33]
Was working perfectly until I updated this morning, now I get this when trying to connect to the same Jenkins server.

"...The resource could not be loaded because the App Transport Security policy requires the use of a secure connection."

**Comment by vloris** [comment]
Same problem here!
Doesn't work for my jenkins-server. The errormessage gave me the idea that https could maybe work, but by jenkins-server only works on http, not https so I can't try it.

**Comment by erikdoe** [comment]
This version is the first one built with the SDK for El Capitan. I now realise that this will trigger App Transport Security when running under El Capitan: https://developer.apple.com/library/ios/technotes/App-Transport-Security-Technote/index.html

Can you confirm that you're running El Capitan? Also, can you please run the following command and provide the output? 

    /usr/bin/nscurl --ats-diagnostics <<url of your server>>

My current assumption is that your Jenkins server uses a certificate that is not deemed secure enough by Apple's new policy.

**Comment by vloris** [comment]
I'm running El Capitan indeed.
I'm not sure what certificate you mean, my jenkins-server only runs on http, not https. Therefore the ats-diagnostics call is not very helpful: it silently converts my given url to https, which fails because there is nothing there.

**Comment by erikdoe** [comment]
I see. My response was to the original report, which didn't mention whether HTTP or HTTPS were used. But thanks to your comment it's now clear that ATS seems to disallow all non-secure connections.

Unfortunately, I can't check this under El Capitan right now, but I have created a version that should disable ATS entirely: https://github.com/erikdoe/ccmenu/releases/tag/v1.10.2d1

Can you check whether that version works for you?

**Comment by anadin** [comment]
I'll check in the morning and sorry yes we use http too. Internal only server.

**Comment by erikdoe** [comment]
Fixed in c2e90fe555e3d913b44ad5ba2ceba60c163acc57. Will be released via the App Store as CCMenu 1.10.2 as soon as possible.

**Comment by mcrispino** [comment]
I had the same problem with version 1.10.1, tried 1.10.2 and worked fine. Thanks for the fix.

**Comment by erikdoe** [comment]
No worries. I have submitted 1.10.2 to the App Store yesterday. It's likely to take a week to get through the process at Apple.

**Comment by bjegannathan-rpx** [comment]
Thanks @erikdoe !

**Comment by erikdoe** [comment]
So, CCMenu has now been rejected in the review process. The complaint is that when you open the preference panel, and have set CCMenu to display a dock icon, and you switch between apps, it is possible to get an empty application menu in the top left corner (right next to the Apple icon). Of course, this is not new behaviour, but the reviewer saw it now. 

Unfortunately, I have no idea how to manipulate that menu. I have tried `[NSApp mainMenu]` but that's not what seems to be used here. Any ideas?

**Comment by bjegannathan-rpx** [comment]
Thanks @erikdoe for your efforts.

**Comment by vloris** [comment]
Works perfectly now! Thanks!
