### ISSUE TITLE
Some status icon color make it difficult to see status

### ISSUE THREAD

**Issue by gcds** [erikdoe/ccmenu#34]
Please change icons colors, because some of them are not distinguished between states on Apple Thunderbolt display and other high brightness monitors.

Thank you!

**Comment by erikdoe** [comment]
When you write "icon colours", I assume you don't refer to the application icon but the status items in the menu bar, right?

Now, these icons are red, green, orange, and grey. Which of these colours cannot be distinguished on an Apple Thunderbolt display?

**Comment by gcds** [comment]
Yes, the status items in the menu bar.

![screen shot 2015-10-13 at 9 50 06 am](https://cloud.githubusercontent.com/assets/15481/10448857/f7dc0b10-718f-11e5-93f3-82a8e4770f9f.png)

The green and orange is almost difficult to see, the grey is like so so... :)

**Comment by erikdoe** [comment]
This is interesting. The colours were chosen by somebody with a visual design background and they have a reasonable difference, except for people who have a colour vision deficiency known as Deuteranopia or red-green blindness. Also these exact colours have been in CCMenu since 2007 and nobody has ever mentioned an issue with them. So, I'm sorry but I have to ask this: are you completely sure that your monitor is calibrated correctly?

**Comment by gcds** [comment]
Tried several different monitors they all have the same problem

![file_000](https://cloud.githubusercontent.com/assets/15481/10450589/8e829f56-719b-11e5-9c4d-7d511638811c.jpeg)

Green it's too bright and causes white to blend in. Other colors is ok

**Comment by erikdoe** [comment]
Oh! So, you are not saying you can't distinguish the orange from the green. You are saying that you can't distinguish the non-building from the building states, ie. you can't see the white chasing arrows easily enough, right?

**Comment by gcds** [comment]
Yes, basically I always need to lean to check if its running

**Comment by erikdoe** [comment]
Do you see #40? Would the icons proposed there work better for you?

**Comment by gcds** [comment]
Yes, they are really cool, and thanks for B&W :+1:

**Comment by erikdoe** [comment]
This is now in master and will be released with the next version.
