### ISSUE TITLE
URL with already-escaped characters incorrectly escaped when opening project in browser

### ISSUE THREAD

**Issue by quiqueg** [erikdoe/ccmenu#36]
If a server URL already has escaped characters in it, clicking on a project causes the `%` character to be escaped when opening the project in a browser.

### Example
Server URL = `https://my.server.com/view/Build%20Artifacts/cc.xml`
URL opened in browser = `https://my.server.com/view/Build%2520Artifacts/job/my_build/`

note that `%25` is the result of escaping a `%` character

### Environment Details
CCMenu version: 1.10.1
OS X version: 10.11
Server type: Jenkins

**Comment by erikdoe** [comment]
This is the result of merging #29, which provided a fix for servers that send un-escaped URLs. At the time I overlooked that it would cause problems in cases where the servers send escaped URLs.

What's the best fix here? If the string contains a percent character already, we assume the URL is escaped and skip the escaping?
