### ISSUE TITLE
Failed do get status http://...: The resource could not be loaded because the App Transport Security policy required the use of a secure connection

### ISSUE THREAD

**Issue by dapi** [erikdoe/ccmenu#38]
This happen after last update. Before it works nice.
![screen shot 2015-10-15 at 8 49 04](https://cloud.githubusercontent.com/assets/31139/10505779/b9598d28-7319-11e5-8e88-5d7e5d2a08e2.png)

CCMenu version: 1.10.1
team city status url: http://teamcity.brandymint.ru/httpAuth/app/rest/cctray/projects.xml/hudson/cc.xml
OS: El Capitan

P.S. Big thanks for CCMenu! It and Trailer are my favorite monitoring apps.

**Comment by erikdoe** [comment]
Please see #33. 

To avoid further duplicates I'll keep this issue open until the new version has made it through Apple's review process.

**Comment by erikdoe** [comment]
Reopened the original bug as the review process didn't go as smoothly as assumed. So, I'm closing this one.
