### ISSUE TITLE
Wrong IP address when I select the project from the menu

### ISSUE THREAD

**Issue by wkundrus** [erikdoe/ccmenu#39]
I have changed the IP of my buildservers. I have recreated the project list under preferences and the status is displayed correctly in the menu, but when I select the menu item, the browser shows the old IP of the project. This makes it impossible to open the project status page from the  menu.

**Comment by erikdoe** [comment]
CCMenu simply opens the links provided by the server. Your server (for some reason) still provides links with the old IP address in the feed to CCMenu. Or, argued the other way round: CCMenu has no invisible configuration and it does not cache anything. This means it has no way to even "remember" the old address.
