### ISSUE TITLE
El Capitan: URL with spaces are not linking correctly

### ISSUE THREAD

**Issue by bragboy** [erikdoe/ccmenu#43]
I have a project in my firewalled environment named "QA Project". Everything works fine except when I click on the taskbar trying to link to it - instead of taking me to `http://ci/job/QA%20Project/` it takes me to `http://ci/job/QA%2520Project/` (Notice the extra characters `25`). I am on Mac OSX El Capitan. Is this a behavior with CC Menu or the OS Behavior ?

Note: This does not happen when I don't have spaces for my project name. For example `QA_Project` works just fine.

Related to https://github.com/erikdoe/ccmenu/pull/29 or https://github.com/erikdoe/ccmenu/pull/41 ?

**Comment by erikdoe** [comment]
Which version of CCMenu are you using? This is a bug that I thought was fixed.

**Comment by bragboy** [comment]
![image](https://cloud.githubusercontent.com/assets/1298587/11068098/d11632ae-87f5-11e5-8189-4315a7fe139e.png)

**Comment by bragboy** [comment]
Hey I think you are right, I updated to the latest version and this issue seem to have been fixed. Thanks!
