### ISSUE TITLE
LAN-based projects link to localhost instead of their hostnames

### ISSUE THREAD

**Issue by mkenyon** [erikdoe/ccmenu#44]
We have Jenkins on our LAN. Its address is http://ci-corporal:8080. When we click on a build in CCMenu, the browser opens to http://localhost:8080 instead.

Here are our projects:

![Our projects points to http://ci-corporal:8080/cc.xml](https://cloud.githubusercontent.com/assets/567950/11094337/345d1cbc-885d-11e5-9e6e-c434848f3638.png)

When we click this application menu:

![Clicking the application menu](https://cloud.githubusercontent.com/assets/567950/11094276/d1482c48-885c-11e5-9081-301389eb4039.png)

Our browser opens at http://localhost:8080 instead of http://ci-corporal:8080

![Takes us to http://localhost:8080](https://cloud.githubusercontent.com/assets/567950/11094304/0005cec8-885d-11e5-91f0-eb118c70c374.png)

**Comment by erikdoe** [comment]
This is a misconfiguration of your Jenkins server. CCMenu simply opens the URL reported by the server. Also see #31.

**Comment by mkenyon** [comment]
Thank you!

For anyone who finds this in the future:

In your Jenkins, click _Manage Jenkins > Configure System_. Then, in the _Jenkins Location_ section, set your _Jenkins URL_ to `http://ci-corporal:8080` (as appropriate).

![configure_system__jenkins_](https://cloud.githubusercontent.com/assets/567950/11094842/17bf9460-8860-11e5-85e0-499ab3c320ac.png)
