### ISSUE TITLE
Encoding issue for project page URL

### ISSUE THREAD

**Issue by ZakTaccardi** [erikdoe/ccmenu#46]
This is the correct URL for the project:

https://app.greenhouseci.com/#/project/79ed1a4b-37ae-4f96-a9ea-d5d7853179d5

But when I click to open the project in the browser, the **#** gets replaced with a **%23**, resulting in a 404 error.

https://app.greenhouseci.com/%23/project/79ed1a4b-37ae-4f96-a9ea-d5d7853179d5

Expected URL:
https://app.greenhouseci.com/#/project/79ed1a4b-37ae-4f96-a9ea-d5d7853179d5

Actual URL:
https://app.greenhouseci.com/%23/project/79ed1a4b-37ae-4f96-a9ea-d5d7853179d5

See http://www.w3schools.com/tags/ref_urlencode.asp

**Comment by erikdoe** [comment]
Sorry, this is the result of #29 and #41. Now CCMenu can handle URLs with spaces and other special characters in them, but it doesn't know that the __#__ character should not be escaped. How hard can it be to open a URL using Apple's frameworks... ;-)

The code is https://github.com/erikdoe/ccmenu/blob/b1560f6f1de3fe526c721cc5e2eb4f4738cd71fd/CCMenu/Classes/NSWorkspace%2BCCMAdditions.m, and it looks like we'd have to use `stringByAddingPercentEncodingWithAllowedCharacters:`. Just not sure what the allowed characters are. I really hope we don't have to split the URL into its components and use different allowed characters for different parts (like hostname, path, etc).

**Comment by erikdoe** [comment]
CCMenu 11.0 containes the fix and has been released on the App Store.
