### ISSUE TITLE
CCMenu sometimes uses a large % of processor cycles

### ISSUE THREAD

**Issue by thomasaw** [erikdoe/ccmenu#48]
I'm seeing an issue where CCMenu sometimes uses a large % of processor cycles (about 10-13% using 10 threads on a MacBook Air (13-inch, Mid 2011)). I don't know the conditions that trigger this, but I've
 attached a sample.

[Sample of CCMenu.txt](https://github.com/erikdoe/ccmenu/files/82095/Sample.of.CCMenu.txt)

**Comment by erikdoe** [comment]
Thank you for including the sample. To be honest, though, even after looking at it I'm not sure what the issue could be. It's obviously something to do with the authentication of HTTPS connections, but what? Is there anything special about your setup? Very large Keychain(s) maybe?

**Comment by thomasaw** [comment]
I have 260 items in my login keychain and 300 items on my iCloud keychain, but I doubt that would be on the large side.

**Comment by erikdoe** [comment]
Doesn't sound large to me either. It's just there's nothing in the samples that would give me an idea what to change in CCMenu. Personally, I don't use the iCloud keychain, so I have no idea whether that could cause issues, but, then again, these would also surface in other apps, right? Or maybe they do an no one has noticed? Or maybe other apps don't make periodic calls to require access to the keychain?

**Comment by thomasaw** [comment]
At this point I'm no longer using the system in question and my current system doesn't have the performance issues with CCMenu.

**Comment by erikdoe** [comment]
In which case I'm going to close this.
