### ISSUE TITLE
Compatibility with Folders plugin

### ISSUE THREAD

**Issue by mremi** [erikdoe/ccmenu#50]
Hello,

CCMenu seems to be not compatible with the [Folders](https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Folders+Plugin) plugin, probably because the related jobs does not appear in `http://jenkins-server/cc.xml`.
Is there any way to configure it or a work in progress to support it?

Thx

**Comment by erikdoe** [comment]
If the jobs don't appear in the `cc.xml` file then CCMenu can't display them. ;-) There isn't anything CCMenu could possibly do here. I would suggest to open an issue with the plugin project.

**Comment by mremi** [comment]
I just found the xml is available at `http://jenkins-server/view/my-view/job/my-folder/cc.xml`...so obvious I didn't test it until now :)
