### ISSUE TITLE
jenkins wrong port

### ISSUE THREAD

**Issue by mariopaumann** [erikdoe/ccmenu#54]
I added project with Port :8080. but when clicking on project in CCMenu it tries port :8000.

http://jenkins:8000/view/CRS/job/CRS-Perl-Parser/

instead of

http://jenkins:8080/view/CRS/job/CRS-Perl-Parser/

**Comment by erikdoe** [comment]
This is a configuration problem with Jenkins. It tells CCMenu the wrong URL. You can check this by opening the feed manually.

**Comment by mariopaumann** [comment]
thank you. found the wrong url in the jenkins system settings
