### ISSUE TITLE
New icons make it hard to find building jobs with lots of jobs

### ISSUE THREAD

**Issue by fkchang** [erikdoe/ccmenu#57]
See my ccmenu, it's really hard for me to find the building job w/the current icon scheme, maybe a different color inside build motion?

![pasted_image_3_24_16__3_08_pm](https://cloud.githubusercontent.com/assets/13941/14032753/5bced9d2-f1d2-11e5-9fa9-284a8c94ebb0.png)

**Comment by ssbarnea** [comment]
I totally support this bug. I reached it by looking for the same error. It does not make much sense to use the same colour for in-progress builds. How about using the blue colour for these builds? The badges are using the same approach: red=failed, green=success, gray=aborted, blue=in-progress.
