### ISSUE TITLE
Only show broken builds in CCMenu

### ISSUE THREAD

**Issue by freakmoder** [erikdoe/ccmenu#61]
I think it would be nice to have an option to only show broken builds in the CCMenu. We have a lot of projects configured on our CI which exceeds the screenspace when all of them are visible in CCMenu window. For me it would be enough to only see the broken builds because these are the only one which needs some attention from my side. I think this wouldn't be a huge task to add an option like this?

**Comment by erikdoe** [comment]
I've implemented this now. Can you check the [pre-release](https://github.com/erikdoe/ccmenu/releases/tag/v12.0d2) and let me know whether that's what you had in mind? I'm asking because I'm now hiding successful builds, which is different from only showing broken ones.

**Comment by freakmoder** [comment]
tested it and its great. Thanks for this fast implementation!
