### ISSUE TITLE
Configuring CCMenu for GoCD which uses GitHub auth

### ISSUE THREAD

**Issue by addisonlee** [erikdoe/ccmenu#63]
We are using GitHub auth for GoCD access. However, CCMenu needs GoCD credentials for authentication. Is there a way to configure CCMenu to authenticate using GitHub instead of GoCD?

**Comment by erikdoe** [comment]
This is not supported yet. GitHub, as well as Google (see #51), use OAuth for their login features. The flows are web-based and normally require client specific secrets; both of which are tricky to implement in an open source desktop applications. 

One alternative would be to allow users to enter tokens directly, as described here: https://github.com/blog/1509-personal-api-tokens. This is less convenient for the user but a lot more easy to implement in CCMenu.

**Comment by erikdoe** [comment]
Just realised this is a duplicate of #49. Closing this one.
