### ISSUE TITLE
Project listing doesn't work for TeamCity 9.1.6 (build 37459)

### ISSUE THREAD

**Issue by ahri** [erikdoe/ccmenu#66]
I paste in my URL: `http://dev:8111/httpAuth/feed.html?buildTypeId=...redacted...&itemsType=builds&buildStatus=successful&buildStatus=failed&userKey=feed`, select "Use URL as entered above", provide my authentication details, and hit "Continue"

CCMenu does some work, and pops up a dialogue saying "Projects:" followed by an empty widget, which I assume should contain some choices for me to add.

When using the same URL with `curl -u adam.piper` I get an XML document with an atom `<feed>`, so the TeamCity end appears to be working.

**Comment by erikdoe** [comment]
CCMenu requires a feed in the "cctray", not an Atom feed. Please see this page on the wiki for installation instructions for vatious servers, including TeamCity: https://github.com/erikdoe/ccmenu/wiki/Supported-Servers

**Comment by ahri** [comment]
Ah! Sorry about that, I'll give it a try on Monday.
