### ISSUE TITLE
Enhancement: Fixed width font for build timing in Menu Bar 

### ISSUE THREAD

**Issue by jimocallaghan** [erikdoe/ccmenu#69]
Hi, I find the timer distracting in the menu bar as items to the left move when the time changes from ex. a time with a zero in it to a one (possibly due to a proportional font being used) - is it possible to try a fixed width font option?

**Comment by erikdoe** [comment]
It is possible, but which font should we use? And will Apple accept the use of an alternative font during the App Store submission process...?

**Comment by jimocallaghan** [comment]
I'm not sure which font is the one to use.  I can see the clock widget that comes with OSX allows display of the seconds also, and this does not suffer from the moment problem.  Perhaps it is not a fixed width issue font issue but more about the container the time is displayed in using a kind of size to fit approach.

**Comment by erikdoe** [comment]
Yes, you are right. I've checked and CCMenu explicitly requests a status bar item with `NSVariableStatusItemLength`. So, one approach would be to calculate a fixed width when the build starts and/or when the number of broken projects change, and then request an item with a fixed length. Marking this as an enhancement request.

**Comment by erikdoe** [comment]
Just realised that there is a font available since OS X 10.11 that's like the system font but with fixed width digits. Using this font greatly reduces the shifting of items in the menu bar. I've decided against a completely fixed width for now, because that would need space for double-digit hours and normally leave a lot of whitespace.

**Comment by jimocallaghan** [comment]
Thanks for the fix Erik
