### ISSUE TITLE
Add support for Jenkins folders

### ISSUE THREAD

**Issue by emanuelez** [erikdoe/ccmenu#73]
Jenkins now supports Folders which is a mechanism to group jobs together. A notable example is the Github Organization Folder plugin which automatically creates a folder of folders of jobs (organization -> job -> branch).

It would be great if ccmenu supported such use-case

**Comment by erikdoe** [comment]
Can you provide an example how folders are represented in the cctray feed? CCMenu can only display information that is in that feed.

**Comment by willcodeforfoo** [comment]
Noticed this as well. I just did a quick glance of our `cc.xml` (we have a GitHub folder that automatically updates with repos/branches) and I didn't see it at all, which is probably why CCMenu doesn't work with them.

**Comment by erikdoe** [comment]
Maybe you can open an issue on Jenkins asking them to add the information to the `cc.xml` file. If you do so, can you post a link to the issue here so that I can watch it? Thanks.

**Comment by willcodeforfoo** [comment]
I learned from that issue that there is a `cc.xml` for each level of the hierarchy, thus the following path worked to show my repos in a subfolder: `https://jenkins.example.com/job/GitHub/job/[github org]/cc.xml` but as that issue mentions, it just shows the branch name, so many repos would be impossible to distinguish between. I just follow the main `master` branch for our repo in CCMenu, so this is an OK workaround.

**Comment by erikdoe** [comment]
I see. So #21 would solve the problem for you. I'm going to close this issue assuming that if and when #21 gets implemented this one is "solved", too.
