### ISSUE TITLE
Add possibility to monitor URL

### ISSUE THREAD

**Issue by KjellMorgenstern** [erikdoe/ccmenu#74]
After successful CI and Deployment, it would be nice to also monitor the freshly deployed API / WebApp.
Nagios seems a bit overkill for that, and having it on the same place as the CCTray would feel natural in a development environment. So it would be great to just setup a URL, which is then requested each few minutes and checked wether reponses are in the 200 range.

Maybe this is possible with little changes to CCMenu?

**Comment by erikdoe** [comment]
Just to confirm, you are really talking about *monitoring* the application, right? You are not intending to use CCMenu to *verify* that the deployment worked, right? If it were the latter, then I would strongly suggest to add a smoke test to your build/deployment scripts, and make the build fail if the deploy didn't work out.

So, assuming we are talking about actual monitoring, I think this would take CCMenu too far away from its focus. CCMenu is about monitoring CI servers, its not a general monitoring tool. Also, if you care about the continued availability of the website (as opposed to verifying that a deploy has worked), then you should probably look into a monitoring solution that can send alerts, e.g. uptimerobot.com.

**Comment by ospfranco** [comment]
If you still need this feature, you can take a look at CI Demon, it's an app I created inspired by CCMenu, it allows you to add simple http ping checks to make sure after your build is finished you can make sure the deployment is working

https://apps.apple.com/de/app/ci-demon/id1560355863?mt=12
