### ISSUE TITLE
Implement monitoring of Gerrit reviews

### ISSUE THREAD

**Issue by ssbarnea** [erikdoe/ccmenu#75]
As a CCMenu user I would like to be able to monitor status change of multiple Gerrit reviews from multiple Gerrit servers. 

Here is how I would translate a review status:
* Minutes votes - failed
* Pending review - in progress
* Plus votes - success

I know that this may seem a little bit outside the original scope of CCMenu but I would find this feature extremely useful and if the features is desired I may try to implement it myself.

Let's hear feedback from others as they may have useful ideas that could share the further development of such a feature.

**Comment by erikdoe** [comment]
Does/could Gerrit provide this information in a [cctray format](https://github.com/erikdoe/ccmenu/wiki/Server-Implementor-Notes) feed?

**Comment by ssbarnea** [comment]
@erikdoe Nope, Gerrit does not provide such a feed and will never do because its not a build server, its a code review tool.

**Comment by erikdoe** [comment]
In which case I will close this issue. Sorry, I am doing CCMenu in my spare time and I neither have the time to write such a feature, nor (in case someone else did it) do I want to add the complexity of supporting multiple data sources to CCMenu, because it will add to maintenance overhead going forward, e.g. Gerrit changes something, the feature breaks in CCMenu, etc.

**Comment by ssbarnea** [comment]
I guess I will end-up writing a proxy/broker that provide this functionality: exposing open CRs/PRs as virtual builds.

Still there is something that would also make integration with CCMenu almost impossible: the fact that these virtual-jobs are really dynamic: you cannot really expect the user to add/remove them manually like we do now with specific entries from the cc.xml file.

**Comment by erikdoe** [comment]
There is #5 that talks about automatically adding new projects... Still not sure how an implementation would look like, though.
