### ISSUE TITLE
Links open in HTTP even when build is configured to be HTTPS.

### ISSUE THREAD

**Issue by twilek** [erikdoe/ccmenu#76]
When clicking on a build in CCMenu, it seems like it opens the link in a browser with HTTP even when the build is configured to use HTTPS.

**Comment by erikdoe** [comment]
This is a misconfiguration of the server. CCMenu simply opens the links the server provides in the feed. If CCMenu opens the wrong link, then the server must have sent it the wrong link. See also #31, #39, #54.
