### ISSUE TITLE
gitlab integration

### ISSUE THREAD

**Issue by patroqueeet** [erikdoe/ccmenu#78]
hey, it would be outstanding and fantastic if using gitlab with ccmenu would be possible...

**Comment by erikdoe** [comment]
Does the Gitlab CI tool support the cctray format? (See [https://github.com/erikdoe/ccmenu/wiki/Server-Implementor-Notes](https://github.com/erikdoe/ccmenu/wiki/Server-Implementor-Notes).) If not, then there's not much I can do. If it does, then CCMenu should work out of the box.

Please let me know if Gitlab CI supports it and if there's a page with setup instructions, I'll happily add it to the page listing the supported servers (also on the wiki).

**Comment by patroqueeet** [comment]
unfortunately I don't find any documentation about it. still gitlab users are a very large crowd and I just wanted to record, that it would be a fantastic thing. I don't know about the other users of ccmenu, but I personally moved all prjs to gitlab and would love to be able to keep using your fantastic tool...

maybe you just want to close this ticket as `noise`. :)

**Comment by erikdoe** [comment]
Yes, I hear you. That said, I do CCMenu in my spare time and I can't manage the complexity of dealing with proprietary APIs for different servers. The only exception I might make is Apple's solution (see #67) but for that I don't even have a test environment.

When the server is open source, there's always the possibility to send a PR that implements a cctray feed to the server's implementors.

**Comment by bborysenko** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/26858

**Comment by patroqueeet** [comment]
@bborysenko yes, seen that. the better approach anyway...

**Comment by ospfranco** [comment]
If you still need gitlab support you can give CI Demon a try, it's an app I created inspired by CCMenu, it does support Gitlab (cloud service)

https://apps.apple.com/de/app/ci-demon/id1560355863?mt=12
