### ISSUE TITLE
auto update mechanism for bleeding edge version

### ISSUE THREAD

**Issue by ssbarnea** [erikdoe/ccmenu#79]
I think that the title is self-explanatory. I would find useful to be able to use the "bleading-edge" version easily, without having to fork-update-fork-compile-and-run-from-xcode.

I think that there are open-source libraries that would help implementing this behaviour easily.

**Comment by erikdoe** [comment]
Yes, there are libraries, and CCMenu used the most popular one from a very early stage (4422d1afaf9d3f035dea561db69e48d5256e724c). Unfortunately, when CCMenu moved to the Mac App Store, I learned that the reviewers don't let applications that contain such code into the store, which means as an app author you have to maintain two separate versions, one for the store, and a stand-alone version with a built-in update mechanism. I did this for a while but in the end felt I couldn't justify the overhead this added to every release. Have a look at the branches labled `mas...` to get an idea; each of them contains the changes made for the Mac App Store version based on the stand-alone version.
