### ISSUE TITLE
Feed URL dropdown is too short hiding critical information

### ISSUE THREAD

**Issue by ssbarnea** [erikdoe/ccmenu#80]
The current server dropdown is not wide enough and prevents the user from picking the right URL.

This is a real issue on instances using folders where you need to use different URLs on the same host, making the re-use of server url a real challenge.

![monosnap 2017-03-27 15-14-54](https://cloud.githubusercontent.com/assets/102495/24360816/4f71dd4c-1300-11e7-8653-a7ee13f374e5.png)

It seems that the shortener algorithm needs to be updated because cutting the last part is not the best idea.

Note: I think that making it even 50% wider it will not solve the problem from this case. As you can see the current width is not enough to fit even the domain name.

**Comment by ssbarnea** [comment]
@erikdoe Can we merge my fix?

**Comment by erikdoe** [comment]
Addressed by making the panel resizable.
