### ISSUE TITLE
Propose cc.xml schema v2

### ISSUE THREAD

**Issue by ssbarnea** [erikdoe/ccmenu#82]
I would like to propose extending the cc.xml schema a little bit in order to address two current limitations: inability to mark unstable builds and providing a link to the build console (in addition to the existing one which is a link to the job doing the builds).

Sadly wikis cannot be forked via GitHub interface so I had to clone it. Here is the proposed version:
https://github.com/ssbarnea/ccmenu/wiki/Multiple-Project-Summary-Reporting-Standard

Once we agree on a specification, I can do the work to update Jenkins implementation to support it, ccmenu being the first client to support it.

**Comment by ssbarnea** [comment]
@erikdoe Any insights regarding my proposal? 

Also maybe we find a way to easy contributions to the wiki, with current limitations (no pull/forks) it seems easier to move the wiki into the source repository.

**Comment by erikdoe** [comment]
In general I like the idea of evolving the cctray format, provided at least one server supports the new new extensions. I haven't had a chance to review the concrete proposal yet.

**Comment by ssbarnea** [comment]
There is a chicken and the egg problem here, especially because nobody owns the `cc.xml` format. So those interested in extending it would wait for someone else to implement it before they follow.

So my proposal is not for implementing it is only about reviewing and accepting a proposed new format. I prefered to use ccmenu for doing this because it has an unique quality: it is the only place that documents the current format.

Once we agree on the format I will do a first implementation for Jenkins. Also I will try contact other cc.xml consumers and inform them about the idea so they could add their input.

If you don't like this approach I could create a github project specially for the the **future development of cc.xml format**... sounds a bit as over engineering the process but whatever makes people happy.

**Comment by erikdoe** [comment]
In order to get the evolution of the cctray format started we have created a dedicated website / git repo (https://github.com/build-canaries/cctray). Let's continue the discussion over there.

I'll close this issue and create a new one as a reminder to add support for JSON formats.
