### ISSUE TITLE
Authentication issue with Jenkins

### ISSUE THREAD

**Issue by rdalverny** [erikdoe/ccmenu#9]
Hi. I have a fresh Jenkins secured setup (TLS on a non-standard port, user account) and, as I merrily went to configure this marvelous CCMenu to fetch those new jobs statuses... it just said no.

To reproduce:
 - OS X 10.10.1, CCMenu 1.8 (266A)
 - feed URL https://user@example.org/cc.xml, "Use URL as entered above" checked, "The server requires..." checked, with valid user/password
 - returns: "The server responded with HTTP status code 403." (triggered at [CCMenu/Classes/CCMProjectSheetController.m#L141](https://github.com/erikdoe/ccmenu/blob/master/CCMenu/Classes/CCMProjectSheetController.m#L141))
 - but, using curl as `curl https://user:pass@example.org/cc.xml`, it works fine, I get the XML feed.
 - and CCMenu works fine with Travis, of course.

Not too sure how to debug this, I checked Jenkins logs that mentioned the CCMenu request to be treated as anonymous. So... I checked both requests details with http://requestb.in and all I could spot was the missing Authorization header when using CCMenu:

```http
Accept-Language: fr-fr
Via: 1.1 vegur
Host: requestb.in
Connect-Time: 63
Connection: close
Accept-Encoding: gzip, deflate
Total-Route-Time: 0
X-Request-Id: 083aa043-5236-49ad-b45b-a7625f5cfcae
User-Agent: CCMenu/266 CFNetwork/720.1.1 Darwin/14.0.0 (x86_64)
Accept: */*
```

Curl does send it:

```http
Via: 1.1 vegur
Host: requestb.in
Connect-Time: 1
Connection: close
Total-Route-Time: 0
X-Request-Id: 0e492527-c74d-4e99-afc4-6114030bc9ed
User-Agent: curl/7.37.1
Authorization: Basic dXNlcjpwYXNz
Accept: */*
```

While writing this report, I found https://wiki.jenkins-ci.org/display/JENKINS/Authenticating+scripted+clients - I quote:
> "Note that Jenkins does not do any authorization negotiation. Ie. it immediately returns a 403 (Forbidden) response instead of a 401 (Unauthorized) response, so make sure to send the authentication information from the first request (aka "preemptive authentication".)"

I am not sure this is the cause, but it would explain why the Authorization header is not sent on requestb.in as well: CCMenu, or CFNetwork would expect a 401 returned by the server before sending auth credentials; alas, Jenkins is not so chatty.

I'm afraid I can't help much on the code level at this point, but I hope this helps find and fix the cause. Thank you so much for CCMenu anyway!

**Comment by rdalverny** [comment]
Just found out http://sourceforge.net/p/ccmenu/bugs/27/ - sorry for the duplicate issue...

Played with fakeserver.rb a bit and I can reproduce the same behavior by returning a 403 in the `protected!` helper. Tracing the requests server-side, it makes a first GET without an `Authentication` header and retries with one if it gets a 401 + `WWW-Authenticate: Basic realm="Restricted Area."` (not returning one or the other fails the negotiation).

I'm testing this with:

```diff
diff --git a/Tools/fakeserver.rb b/Tools/fakeserver.rb
index 4ecfde3..2879d4b 100644
--- a/Tools/fakeserver.rb
+++ b/Tools/fakeserver.rb
@@ -19,6 +19,11 @@ helpers do
     halt 401, "Not authorized\n"
   end
 
+  def jenkins_protected!
+    return if authorized?
+    halt 403
+  end
+
   def authorized?
     @auth ||=  Rack::Auth::Basic::Request.new(request.env)
     @auth.provided? and @auth.basic? and @auth.credentials and @auth.credentials == ['dev', 'rosebud']
@@ -67,6 +72,12 @@ get '/protected/cctray.xml' do
   haml :cctray
 end
 
+get '/jenkins_protected/cctray.xml' do
+  jenkins_protected!
+  content_type :xml
+  haml :cctray
+end
+
 get '/weird/cctray.xml' do
   halt 500, 'oops!'
 end
```

One solution could be to force sending the `Authentication: Basic base64(username:password)` header, only when "The server requires authentication" checkbox is on. But:

 * I'm stuck - not proficient enough to see all the places to check, or how to refactor, if ever needed: `CCMSyncConnection::testConnection`, `retrieveServerStatus`, `CCMConnection::requestServerStatus`? other?
 * so far, I can make it work for a first connection, but it fails at the subsequent ones, so it's still useless.

**Comment by eeichinger** [comment]
I can confirm this to be a problem with the latest version CCMenu 1.8. Some observations

(On a sidenote: you want to use the API token instead of a password for connecting:
https://<username>:<api-token>@<server>/jenkins/cc.xml)

1. It appears that the Apple HTTP Client lib doesn't send an Authorization header as long as it is not challenged with a 401

2. This can be reproduced by simply - as a logged out user! - entering the url https://<username>:<api-token>@<server>/jenkins/cc.xml into Safari. It will still redirect Jenkins' login page

3. With CCMenu 1.7 it was at least possible to authenticate in the Safari browser with Safari. Subsequently CCMenu was able to access the jenkins url as well. With CCMenu 1.8 this doesn't seem to be the case anymore

**Comment by erikdoe** [comment]
Have seen the PR and will comment on that over there. Regarding the issue, does anyone have an explanation why the changes that were made in CCMenu 1.8 would cause this issue? Disregarding some refactorings the key change in this area was the addition of this _if_ statement https://github.com/erikdoe/ccmenu/blob/master/CCMenu/Classes/CCMConnection.m#L85-97, which is all about server trust. The code just below, which deals with authorisation, should really be unchanged. I must say I'm a bit puzzled.

**Comment by erikdoe** [comment]
Following on from this. Can someone provide a full response from Jenkins? What exactly does the "empty" Jenkins response look like? Is there maybe something in the HTTP response headers that could help CCMenu realise it is talking to a Jenkins sever that has this authentication issue?

**Comment by rdalverny** [comment]
Here a sample:

```HTTP
$ curl -i https://testserver.example.org/cc.xml
HTTP/1.1 403 Forbidden
Set-Cookie: JSESSIONID.165fd97d=p3nnelts5k71baljsglq0wtq;Path=/;Secure;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: text/html;charset=UTF-8
X-Hudson: 1.395
X-Jenkins: 1.596
X-Jenkins-Session: b7163336
X-Hudson-CLI-Port: 49949
X-Jenkins-CLI-Port: 49949
X-Jenkins-CLI2-Port: 49949
X-You-Are-Authenticated-As: anonymous
X-You-Are-In-Group: 
X-Required-Permission: hudson.model.Hudson.Read
X-Permission-Implied-By: hudson.security.Permission.GenericRead
X-Permission-Implied-By: hudson.model.Hudson.Administer
Content-Length: 805
Server: Jetty(winstone-2.8)

<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fcc.xml'/><script>window.location.replace('/login?from=%2Fcc.xml');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:
  
Permission you need to have (but didn't): hudson.model.Hudson.Read
 ... which is implied by: hudson.security.Permission.GenericRead
 ... which is implied by: hudson.model.Hudson.Administer
-->

</body></html> 
```

**Comment by erikdoe** [comment]
Closing this as fixed. See #11 for details.
