### ISSUE TITLE
maintenance and future of ccmenu?

### ISSUE THREAD

**Issue by ssbarnea** [erikdoe/ccmenu#98]
@erikdoe First let me thank you for creating this ccmenu as over the years it was one of my favourite tools. 

Still, apparently based on number of tickets and pull requests open, you don't have spare time to invest on it. Do you have any plans to restart working on it or to let someone else takeover its burden?

I am asking this because I seen few forks and pull requests which make me think that there are a bunch of people that would like to work on improving it. Obviously that someone needs to perform reviews, merges and make releases. Any ideas?

**Comment by erikdoe** [comment]
Thank you for the compliment. I am glad to hear that you like CCMenu. Regarding maintenance of CCMenu, it is actually a joy for me, not a burden.

That said, you are right in that I can't spend as much time as I'd like working on CCMenu. So, I would appreciate any help with the open issues; especially the ones flagged as "help wanted". If you are interested in one of the issues that is flagged as "enhancement" please drop a quick comment in the issue to coordinate.

Your message is also a good reminder that I should close the open PR's that will not get merged. I got a bit sloppy there.
