### ISSUE TITLE
Cannot retrieve project information : NSPlaceholderDictionary initWithObjects:forKeys:count:

### ISSUE THREAD

**Issue by ssbarnea** [erikdoe/ccmenu#99]
I latest build from master I got this error while trying to add a new cc.xml url:

Cannot retrieve project information
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[3]

I mention that the same URL works in browser.

**Comment by erikdoe** [comment]
Do you get this all the time? Or only for certain URLs? I'm asking because I can't reproduce the issue.

**Comment by erikdoe** [comment]
Closing due to lack of information and inactivity.

**Comment by Pysis868** [comment]
I have been trying to get our updated Jenkins server to work with CCMenu again and am having this issue.
Our old server was using insecure HTTP, a port number, and required my username.
The original URL gives a 403 now, and I suspect a redirect.
The new URL: `https://<hostname>/cc.xml`
I'm not sure if basic authentication is enabled for the server.

I retired this Sample XML Format while authenticated through the browser and queried from there:
```
<Projects>
  <Project activity="<job_status>" lastBuildStatus="<build_status>" lastBuildLabel="<build_number>" webUrl="https://<hostname>/job/<jobName>/" name="<jobName>" lastBuildTime="<build_time>"/>
  ...
</Projects>
```

**Comment by Pysis868** [comment]
Just tried again today while looking for a sort of log file.  Didn't find much, but was looking in Mac Console using the search keyword "CCMenu".
It mostly just had generic network connection info messages, but when I reproduced a URL of the format "https://<username>@<hostname>/cc.xml" for our new server, and also having changed my password for the system lately, it worked.

**Comment by erikdoe** [comment]
There is a workaround in CCMenu for Jenkins' weird behaviour. (It shouldn't use a redirect and HTML login page for a resource to be consumed by machines.) That said, the workaround doesn't seem to get triggered in your case. Is there any chance that there is a proxy / reverse proxy between you and the Jenkins server, which strips out header fields? I'm asking because the workaround is triggered by the presence of a header that Jenkins sends.

**Comment by erikdoe** [comment]
And regarding the "parsing issue" you suspect. When you put the username and password into the URL for `curl` than it will send the username and password, whether the server expects it or not. In that case Jenkins will return the XML feed. The problem is that when the username and password isn't sent, then Jenkins doesn't follow the HTTP conventions to request authentication, but it returns an HTML page instead; try running `curl` without the username/password...

**Comment by Pysis868** [comment]
So completely without:

```
⋊> ~ curl -v 'https://<hostname>/cc.xml'
*   Trying ###.###.###.###...
* TCP_NODELAY set
* Connected to <hostname> (###.###.###.###) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=...; ST=...; L=Cary; O=...; OU=...; CN=*.<hostname_parent_domain>
*  start date: Jul  9 00:00:00 2018 GMT
*  expire date: Oct 11 00:00:00 2020 GMT
*  subjectAltName: host "<hostname>" matched cert's "*.<hostname_parent_domain>"
*  issuer: C=...; O=...; CN=...
*  SSL certificate verify ok.
> GET /cc.xml HTTP/1.1
> Host: <hostname>
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Server: nginx/1.12.2
< Date: Mon, 05 Nov 2018 14:25:59 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 805
< Connection: keep-alive
< X-Content-Type-Options: nosniff
< Set-Cookie: JSESSIONID....=...;Path=/;Secure;HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< X-Hudson: 1.395
< X-Jenkins: 2.121.3
< X-Jenkins-Session: ...
< X-Hudson-CLI-Port: 33835
< X-Jenkins-CLI-Port: 33835
< X-Jenkins-CLI2-Port: 33835
< X-You-Are-Authenticated-As: anonymous
< X-You-Are-In-Group-Disabled: JENKINS-...: use -Dhudson.security.AccessDeniedException2.REPORT_GROUP_HEADERS=true or use /whoAmI to diagnose
< X-Required-Permission: hudson.model.Hudson.Read
< X-Permission-Implied-By: hudson.security.Permission.GenericRead
< X-Permission-Implied-By: hudson.model.Hudson.Administer
<
<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fcc.xml'/><script>window.location.replace('/login?from=%2Fcc.xml');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:

Permission you need to have (but didn't): hudson.model.Hudson.Read
 ... which is implied by: hudson.security.Permission.GenericRead
 ... which is implied by: hudson.model.Hudson.Administer
-->

* Connection #0 to host <hostname> left intact
</body></html>
```

**Comment by erikdoe** [comment]
This is strange. The response you get is the typical Jenkins authentication response, which the following code in CCMenu identifies: https://github.com/erikdoe/ccmenu/blob/26fb1d255d3db9df1d484254a7482818e667e116/CCMenu/Classes/CCMConnection.m#L203-208

Once CCMenu sees such a response it knows it's dealing with Jenkins and then pushes username and password: https://github.com/erikdoe/ccmenu/blob/26fb1d255d3db9df1d484254a7482818e667e116/CCMenu/Classes/CCMConnection.m#L78-79 

I have really no idea why this wouldn't work in your case. If you are comfortable debugging a Mac app, you could want to have a look at the two places I linked above and see what's happening.
